import react from "../../assets/img/svg/reactImage.svg";
import metal from "../../assets/img/svg/metalImage.svg";
import proton from "../../assets/img/svg/proton.svg";
import dollar from "../../assets/img/svg/dollarImage.svg";
import bitcoin from "../../assets/img/svg/bitcoin.svg";
import ethrum from "../../assets/img/svg/etrhrum.svg";
import token from "../../assets/img/svg/token.svg";
import doge from "../../assets/img/svg/doge.svg";
import tokenLast from "../../assets/img/svg/tokenlast.svg";
import home from "../../assets/img/svg/home.svg";

export const myCard = [
  {
    img: react,
    h3: "Proton Blockchain",
    para: " $XPR",
    para1: "APR",
    paragraph: " Proton Blockchain ($XPR) is the native",
    span: "  cryptocurrency of the Proton Blockchain.",
    para2: " 27%",
    para3: " My stake",
    para4: " $0.0012324",
    para5: " My rewards",
    para6: " $20,372,275",
    para7: " Remaining rewards",
    para8: " 9,93,031.75",
    para9: " Total Stake reward",
    para10: " 1,029,993,031.75",
    btn: " Add tokens to staking pool",
  },
  {
    img: metal,
    h3: "Metal DAO",
    para: " $METAL",
    paragraph: " Metal Blockchain ($METAL) is the native  ",
    span: " cryptocurrency of the Metal Blockchain.",
    para1: "APR",
    para2: " 27%",
    para3: " My stake",
    para4: " $0.0012324",
    para5: " My rewards",
    para6: " $20,372,275",
    para7: " Remaining rewards",
    para8: " 9,93,031.75",
    para9: " Total Stake reward",
    para10: " 1,029,993,031.75",
    btn: " Add tokens to staking pool",
  },
  {
    img: proton,
    h3: "Proton Loan",
    para: " $LOAN",
    para1: "APR",
    paragraph: " Proton Loan ($LOAN) is the native token ",
    span: " of the Proton Loan ecosystem.",
    para2: " 27%",
    para3: " My stake",
    para4: " $0.0012324",
    para5: " My rewards",
    para6: " $20,372,275",
    para7: " Remaining rewards",
    para8: " 9,93,031.75",
    para9: " Total Stake reward",
    para10: " 1,029,993,031.75",
    btn: " Add tokens to staking pool",
  },
  {
    img: dollar,
    h3: "Metal Dollar",
    para: " $XMD",
    para1: "APR",
    paragraph: " Metal Dollar ($XMD) is the world’s first ",
    span: " basket of non-algorithmic industry.",
    para2: " 27%",
    para3: " My stake",
    para4: " $0.0012324",
    para5: " My rewards",
    para6: " $20,372,275",
    para7: " Remaining rewards",
    para8: " 9,93,031.75",
    para9: " Total Stake reward",
    para10: " 1,029,993,031.75",
    btn: " Add tokens to staking pool",
  },
  {
    img: bitcoin,
    h3: "Bitcoin",
    para: " $BTC",
    para1: "APR",
    paragraph: " Metal Blockchain ($METAL) is the native  ",
    span: " cryptocurrency of the Metal Blockchain.",
    para2: " 27%",
    para3: " My stake",
    para4: " $0.0012324",
    para5: " My rewards",
    para6: " $20,372,275",
    para7: " Remaining rewards",
    para8: " 9,93,031.75",
    para9: " Total Stake reward",
    para10: " 1,029,993,031.75",
    btn: " Add tokens to staking pool",
  },
  {
    img: ethrum,
    h3: "Ethereum",
    para: " $ETH",
    para1: "APR",
    paragraph: " Metal Blockchain ($METAL) is the native  ",
    span: " cryptocurrency of the Metal Blockchain.",
    para2: " 27%",
    para3: " My stake",
    para4: " $0.0012324",
    para5: " My rewards",
    para6: " $20,372,275",
    para7: " Remaining rewards",
    para8: " 9,93,031.75",
    para9: " Total Stake reward",
    para10: " 1,029,993,031.75",
    btn: " Add tokens to staking pool",
  },
  {
    img: token,
    h3: "Token",
    para: " $METAL",
    para1: "APR",
    paragraph: " Metal Blockchain ($METAL) is the native  ",
    span: "  cryptocurrency of the Metal Blockchain.",
    para2: " 27%",
    para3: " My stake",
    para4: " $0.0012324",
    para5: " My rewards",
    para6: " $20,372,275",
    para7: " Remaining rewards",
    para8: " 9,93,031.75",
    para9: " Total Stake reward",
    para10: " 1,029,993,031.75",
    btn: " Add tokens to staking pool",
  },
  {
    img: doge,
    h3: "Dogecoin",
    para: " $METAL",
    para1: "APR",
    paragraph: "Metal Blockchain ($METAL) is the native  ",
    span: "cryptocurrency of the Metal Blockchain.",
    para2: " 27%",
    para3: " My stake",
    para4: " $0.0012324",
    para5: " My rewards",
    para6: " $20,372,275",
    para7: " Remaining rewards",
    para8: " 9,93,031.75",
    para9: " Total Stake reward",
    para10: " 1,029,993,031.75",
    btn: " Add tokens to staking pool",
  },
  {
    img: tokenLast,
    h3: "Token",
    para: " $METAL",
    para1: "APR",
    paragraph: "Metal Blockchain ($METAL) is the native  ",
    span: "  cryptocurrency of the Metal Blockchain.",
    para2: " 27%",
    para3: " My stake",
    para4: " $0.0012324",
    para5: " My rewards",
    para6: " $20,372,275",
    para7: " Remaining rewards",
    para8: " 9,93,031.75",
    para9: " Total Stake reward",
    para10: " 1,029,993,031.75",
    btn: " Add tokens to staking pool",
  },
  {
    img: home,
    h3: "Token",
    para: " $METAL",
    para1: "APR",
    paragraph: "Metal Blockchain ($METAL) is the native  ",
    span: "cryptocurrency of the Metal Blockchain.",
    para2: " 27%",
    para3: " My stake",
    para4: " $0.0012324",
    para5: " My rewards",
    para6: " $20,372,275",
    para7: " Remaining rewards",
    para8: " 9,93,031.75",
    para9: " Total Stake reward",
    para10: " 1,029,993,031.75",
    btn: " Add tokens to staking pool",
  },
  {
    img: metal,
    h3: "Dogecoin",
    para: " $METAL",
    para1: "APR",
    paragraph: "Metal Blockchain ($METAL) is the native ",
    span: " cryptocurrency of the Metal Blockchain.",
    para2: " 27%",
    para3: " My stake",
    para4: " $0.0012324",
    para5: " My rewards",
    para6: " $20,372,275",
    para7: " Remaining rewards",
    para8: " 9,93,031.75",
    para9: " Total Stake reward",
    para10: " 1,029,993,031.75",
    btn: " Add tokens to staking pool",
  },
  {
    img: metal,
    h3: "Token",
    para: " $METAL",
    para1: "APR",
    paragraph: "Metal Blockchain ($METAL) is the native  ",
    span: " cryptocurrency of the Metal Blockchain.",
    para2: " 27%",
    para3: " My stake",
    para4: " $0.0012324",
    para5: " My rewards",
    para6: " $20,372,275",
    para7: " Remaining rewards",
    para8: " 9,93,031.75",
    para9: " Total Stake reward",
    para10: " 1,029,993,031.75",
    btn: " Add tokens to staking pool",
  },
];
